name: Schedule Daily Operation

on:
    schedule:
        - cron: "0 2 * * *" # Runs at 2:00 AM UTC every day

jobs:
    trigger_daily_operation:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Vercel Edge Function
              run: |
                  curl -X GET "https://grand-line.kbueno-studio.com/api/edgyFunction"
